### ISSUE TITLE
I can't press run button

### ISSUE THREAD

**Issue by danielriverolosa** [scala-exercises/exercises-scalatutorial#15]
When i try to solve the exercise, i can't press run button, neither in the mobile browser nor in the computer browser.

That could be happening?

**Comment by bbichero** [comment]
In which exercice ?
All ?
Perhabs your browser. Do you use google chrome ? IE ?

**Comment by danielriverolosa** [comment]
All exercises, im using google chrome.

**Comment by danielriverolosa** [comment]
The button appears disable

**Comment by bbichero** [comment]
Ok, have you enter some value in blank fields ?

**Comment by danielriverolosa** [comment]
Yes, of course, i am trying in firefox and showed the same problem.

**Comment by bbichero** [comment]
Send screen shots please.

**Comment by danielriverolosa** [comment]
![captura de pantalla de 2017-06-09 01-41-51](https://user-images.githubusercontent.com/23519518/26955098-e4b2df6c-4cb4-11e7-8188-1bde321d6fec.png)

**Comment by bbichero** [comment]
Don't know what to tell you. I have to probleme to submit exercices ...
Sorry.

**Comment by danielriverolosa** [comment]
Thanks

**Comment by AdrianRaFo** [comment]
Are you logged? You must be logged to run exercises

**Comment by bbichero** [comment]
Ho yes sorry I think that wasn't required.
90% sure this will resolv issuel

**Comment by danielriverolosa** [comment]
Yes, yesterday i tried to login and it showed an error. Today i tried and everything works correctly!
Thanks!!!

**Comment by Invis1bleReborn** [comment]
I have the same issue, I can't press buttons after filling blank fields because it is disabled. I already logged in via GitHub.
