### ISSUE TITLE
Syntax isn't introduced

### ISSUE THREAD

**Issue by ejflick** [scala-exercises/exercises-scalatutorial#23]
There's no point where the following syntax is introduced:
https://github.com/scala-exercises/exercises-scalatutorial/blob/23b132f382e2372ac5ee3e00fc3e70aaa480be30/src/main/scala/scalatutorial/sections/StandardLibrary.scala#L120

Even trying to scour the internet, it's difficult to find the solution that's expected.

**Comment by albertocamposblanco** [comment]
You need to make a statement similar to a map:

(x,y) => (x<=y)

You assign x,y as your two parameters and map them to the comparison you want to run later.

Hope this helps.

**Comment by 17hao** [comment]
I think (Int,Int) => Boolean means a type

You can understand it like a type(Int,Double,Long...)

the right answer is:   _val cond:(Int,Int)=>Boolean = (x:Int,y:Int)=>x<y_

**Comment by milan-marinov-usu** [comment]
I had the same problem, this syntax is not previously introduced in the tutorial. Really not a good way to teach Scala. Thanks a lot to @albertocamposblanco, his solution was the key to complete the exercise: (x,y) => (x<y)

**Comment by tulth** [comment]
As a scala newbie, I found this confusing as well.
I expected the answer to be:
```scala
val cond: (Int, Int) => Boolean = <
````

Is there a way of referring to the lessThan operator function in the built-ins?

**Comment by Nboaram** [comment]
Yeah, I found this incredibly confusing as well, maybe an example of a similar condition being used earlier would help?
