### ISSUE TITLE
Scala Tutorial: the last exercise of Lazy Evaluation, builder.result() shouldBe "xyzz" 

### ISSUE THREAD

**Issue by KnightGreen** [scala-exercises/exercises-scalatutorial#38]
ran it on scala 2.10.7 and the result is "xyzz", but this answer cannot pass,  is something wrong?

**Comment by FRosner** [comment]
Thanks for reporting this @KnightGreen. I'll take a look.

Can you please provide screenshots of the error?

From what you have learned in the chapter, what do you think the correct answer should be? Independent of what Scala 2.10.7 says.

**Comment by KnightGreen** [comment]
<img width="1058" alt="issue" src="https://user-images.githubusercontent.com/11594338/40704559-0112795a-641b-11e8-8ee9-e5c9faa70956.png">

Got the right answer, the case for the previous result "xyzz" probably is that I run it on the worksheet which interactively run the evaluation. Sorry for this misreporting.

**Comment by FRosner** [comment]
No problem. Glad you enjoy the site! :)
