### ISSUE TITLE
Exercises with nothing to fill in / impossible to complete

### ISSUE THREAD

**Issue by jrgonzalezg** [scala-exercises/exercises-scalatutorial#5]
There are 3 "exercises" with nothing to fill in that can't be run or be marked as completed (so the corresponding sections can't also be counted as completed). The affected sections are:

- [Structuring information](https://www.scala-exercises.org/scala_tutorial/structuring_information): The exercise on Exhaustivity
- [Classes Vs Case Classes](https://www.scala-exercises.org/scala_tutorial/classes_vs_case_classes): Empty exercise at the end of the section
- [Lazy Evaluation](https://www.scala-exercises.org/scala_tutorial/lazy_evaluation): Empty exercise at the end of the section

Hope this helps and thanks for all the nice exercises!

**Comment by julienrf** [comment]
Hi, thanks for reporting. However, we are aware of these issues: https://github.com/scala-exercises/scala-exercises/issues/619.

**Comment by jrgonzalezg** [comment]
Sorry, i did not think of checking for duplicate issues on the other repository!

**Comment by julienrf** [comment]
No problem, thank you again for reporting issues!
